### ISSUE TITLE
Google translate wants verification

### ISSUE THREAD

**Issue by emicom** [trespassersW/UserScripts#1]
Google translate wants verification on translation. 
Google response: https://translate.google.com/translate_a/t?client=t&text=verification&hl=bg&sl=en&tl=bg
div> IP address: 46.55.156.121
Time: 2015-04-09T07:19:53Z
URL: https://translate.google.com/translate_a/t?client=t&text=verification&hl=bg&sl=en&tl=bg

My IP address is not in any ban list to my knowledge. It first begun few days ago. Interestingly enough I am logged on my google account and on google translate page I have no any problem.

About this page
Our systems have detected unusual traffic from your computer network. This page checks to see if it's really you sending the requests, and not a robot. Why did this happen?

https://ipv4.google.com/sorry/IndexRedirect?continue=https://translate.google.com/translate_a/t%3Fclient%3Dt%26text%3Daddress%26hl%3Dbg%26sl%3Dbg%26tl%3Den&q=CGMSBC43nHkYk9KYqQUiGQDxp4NLAx1G4NoL8jJiPGJp4aP3xTDYGGk

This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the Terms of Service. The block will expire shortly after those requests stop. In the meantime, solving the above CAPTCHA will let you continue to use our services.
This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests. If you share your network connection, ask your administrator for help — a different computer using the same IP address may be responsible. Learn more
Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly. 

Used browser: Pale Moon 25.3.1

**Comment by trespassersW** [comment]
The problem has been solved , i hope so :blush:
translate.google service is still  working thru POST requests.

**Comment by trespassersW** [comment]
Re: [UserScripts] Google translate wants verification (#1)






hi, emicom
 You wrote Thursday, April 09, 2015, 10:28:21:
> Google translate wants verification on translation.
 I hope I fixed it, my script now use 'POST' requests to access google translate service, it seems working without verification.
Also, <a href=https://openuserjs.org/scripts/trespassersW/translate.google_tooltip>translate.google tooltip</a> is now available on OpenUserJs.org

trespassersW                          mailto:okapi1788@gmail.com

**Comment by emicom** [comment]
Yep, problem solved. Including the home url for the script update. Thanks for the fast reply. :) And Thank you for the wonderful script I've used for years. Спасибо

**Comment by emicom** [comment]
Again the same problem arise - google verification

**Comment by trespassersW** [comment]
Seems fixed. However, I do not know how long it will live ...

**Comment by emicom** [comment]
Thank you. :)

**Comment by trespassersW** [comment]
I proudly announce that I <a href=https://github.com/greasemonkey/greasemonkey/issues/2221#issuecomment-125948063>fixed</a> another <a href=https://greasyfork.org/en/forum/discussion/5274/x#Comment>problem</a> arisen in Ff39 :sunglasses:

**Comment by trespassersW** [comment]
:neutral_face:

**Comment by emicom** [comment]
Google again make trouble with the script. Shall we wait for an update soon?

**Comment by trespassersW** [comment]
seems repaired and should work for some time

**Comment by emicom** [comment]
@trespassersW , your script is amazing and I've use it for very long time. Thank you.
May I have a question? Is it possible to incorporate into this script also Microsoft translator? Similar to Google "Translate Client"? Your script is better than Translate Client - it is more handy and practical to use. Sometimes Google give awful translation and Microsoft is better in some cases.
http://translateclient.com/
Thank you again for your huge effort in helping all of us with your amazing script. :)

**Comment by trespassersW** [comment]
Thanks for the kind words, @emicom

>  Sometimes Google give awful translation 

fully agreed

> also Microsoft translator?

I am thinking about it. 
But,  if I'll do  it --  I will have to rename my script to <b>translate.google.ms tooltip</b> :neutral_face:

**Comment by Martii** [comment]
> Sometimes Google give awful translation and Microsoft is better in some cases.

Run into that myself on occasion.

>  I will have to rename my script to translate.google.ms tooltip

You'll have current Admin support on OUJS for this if you so choose. :)
