### ISSUE TITLE
translate.google_tooltip: GM4 and perhaps first run show options

### ISSUE THREAD

**Issue by Martii** [trespassersW/UserScripts#10]
Heyo,

Would it be possible to amend the script to check [`GM_info.scriptHandler`](https://wiki.greasespot.net/GM.info) and `GM_info.version` to check for GM4 and auto-open the options dialog since `GM_registerMenuCommand` doesn't exist [there](https://wiki.greasespot.net/Greasemonkey_Manual:API) anymore?

Still have that issue where `Alt` + click is an OS level reserved key combo and I'd like to attempt to get this .user.js runnning in Fx with GM4.

Thanks for the consideration.

**Comment by trespassersW** [comment]
GM4 has too many issues... So I use <b>TamperMonkey</b>, wich is fullly compatible with classic GM.

**Comment by Martii** [comment]
[TM is compatible with the GM.* API as well](https://github.com/Tampermonkey/tampermonkey/issues/579#issuecomment-406954289) but thought I'd try to improve your usage again across different combinations especially for those of us that have to test things across everything. Thanks though... will have to deal with the issues with TM which seem to be greater at the moment than GM itself.
