### ISSUE TITLE
translate.google tooltip: Window movement instead of expected behavior

### ISSUE THREAD

**Issue by Martii** [trespassersW/UserScripts#2]
Heyo. I thought I'd give [this user script](https://openuserjs.org/scripts/trespassersW/translate.google_tooltip) a whirl but found that if I follow the instructions of:

> Select word or phrase with Alt key pressed - then hover over an icon below the selection.

... this moves the active window around the screen e.g. KDE has control of that modifier key and mouse drag operation.

Any ideas? I shouldn't have to modify my settings in KDE though. TIA :)

**Comment by trespassersW** [comment]
So, after text selection with Alt key, KDE starts dragging active window on any mouse movement? did I understand you correctly?

**Comment by Martii** [comment]
> ... after text selection with Alt key ...

The moment I press the Alt key and then try to select any text it drags the window instead.

**Comment by Martii** [comment]
So this is a way to get it working "out of the box" with KDE System Settings:
1. Open this...<br /> ![kdesettings1spotlight opt](https://cloud.githubusercontent.com/assets/114709/10270395/85b4d974-6aad-11e5-903d-47f58d2932ec.png)
2. Goto this...<br /> ![kdesettings2spotlight opt](https://cloud.githubusercontent.com/assets/114709/10270396/8d4d8014-6aad-11e5-9f98-605b43454abb.png)
3. Change to this...<br /> ![kdesettings3spotlight opt](https://cloud.githubusercontent.com/assets/114709/10270397/90470f1a-6aad-11e5-99d1-18af052c3774.png) <br /> _(`Meta` key is usually the `ctrl` key on PC's, or on Macintosh keyboards they can be different keys... they have the `command` key (&#x2318;) and `control` key on classic keyboards. For example this:<br />![condensedmackybd opt](https://cloud.githubusercontent.com/assets/114709/10270607/3e5c2490-6ab4-11e5-88b4-df187f826e97.png))_

Additionally this script is "out of the box" **incompatible** with https://addons.mozilla.org/addon/flashgot/  and needs the following change in FlashGot to work with your script "out of the box":
1. Goto this...<br /> ![flashgot1spotlight opt](https://cloud.githubusercontent.com/assets/114709/10270400/9776fc3c-6aad-11e5-8acb-748aa7c87105.png)
2. Change to this...<br /> ![flashgot2spotlight opt](https://cloud.githubusercontent.com/assets/114709/10270405/a7035128-6aad-11e5-8bb2-84ad948876fa.png)

After your "out of the box" script can be activated with the above changes ... then I can change the modifier key to use `Ctrl` and `Alt` in your script and restore both KDE settings and FlashGots settings back to "out of the box":
1. Translate [this comment](https://openuserjs.org/scripts/uk/24ur.com_brez_oglasov/issues/Ne_deluje#comment-15008f45f4c)...<br /> ![translategoogletooltipspotlight opt](https://cloud.githubusercontent.com/assets/114709/10270406/ae54909a-6aad-11e5-9abd-94e49538429f.png)

This raises a few questions perhaps with a few requests for enhancement:
- Is there an easy way to change to "Ctrl" and "Alt" e.g. bring up just that user interface on fresh installs of your script without having to use a modifier key?
- Does this user script only translate one sentence at a time?

**Comment by trespassersW** [comment]
<i>I wrote this just before I read your last post ::</i>
I'd suggest the following: 
-  Alt-double-click any word in text;
  the word should be selected and script's icon should appear;
- if so, hover over it and, in options dialog, alter these check-boxes:
- <code>Use with: ☑ Ctrl  ☐   Alt</code>;
- press <strong>save</strong>
- thereafter the script will run on ctrl-select combination.

---

> Does this user script only translate one sentence at a time?

 That's Google who stops translation when it detects the end of sentence

> Is there an easy way to change to "Ctrl" and "Alt" 

 Yes, I thought about it. Probably , it is necessary to add an item called 'translate.google options' into Greasemonkey's 'User Script Commands' menu.

**Comment by Martii** [comment]
> Alt-double-click any word in text; the word should be selected and script's icon should appear

Looks like KDE is early binding on keyboard scan codes... so this possibility doesn't work at this time.

> That's Google who stops translation when it detects the end of sentence

Well that bites. ;) :) ... **EDIT**: still a very nice script even with some hurdles.

> 'translate.google options' into Greasemonkey's 'User Script Commands' menu

That's about all I can think of myself since this script runs anywhere. It is difficult to find a common place in all websites user interface to put something like that. Not sure how you feel about floating preferences on by default "out of the box".

Thanks for your assistance/ears/eyes! :)

**Comment by trespassersW** [comment]
> That's Google who stops translation when it detects the end of sentence

No, I was wrong. Now fixed.
Plus, I have added GM_menu item.

**Comment by Martii** [comment]
*Goes eagerly to try it out* :)

**Comment by Martii** [comment]
WOW! Very nice. Thank you! :) If I could rate your script higher, legally and ethically, I would! Nice work!

**Comment by Martii** [comment]
Retested on clean and well used profiles with:

``` sh-session
Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101 SeaMonkey/2.38 (moz 64 bit build) with GM Port
Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0 (distro 64 bit build) with GM
```

.... and everything is **awesome**... closing as you made life a lot easier for new installers with KDE. :) Thanks again and keep up the great work.

**Comment by trespassersW** [comment]
Thank you Marty for your gentle review.
I'll be trying to maintain  my modest script alive as long as I can..
