### ISSUE TITLE
translate.google_tooltip: > Bad Google Response Error 411 (Length required)!!1

### ISSUE THREAD

**Issue by Martii** [trespassersW/UserScripts#3]
Happens with full translation quote of:

> Это точно. Выдаваемые Яндексом результаты зависят от множества факторов - во-первых, от ваших настроек Яндекса; от источника запроса; от истории ваших запросов; от модели и версии браузера; от вашего IP (по которому вычисляется ваше местоположение); от постоянно меняющегося яндекс-рейтинга сайтов, и еще от множества причин, включая погоду на марсе... -- очень диссертабельная тема для исследований.

... but not the partial of:

> Это точно. Выдаваемые Яндексом результаты зависят от множества факторов - во-первых, от ваших настроек Яндекса; от источника запроса; от истории ваших запросов; от модели и версии браузера; от вашего IP (по которому вычисляется ваше местоположение); от постоянно меняющегося яндекс-рейтинга сайтов, и еще от множества причин, включая погоду на марсе.

Refs:
- [OUJS source](https://openuserjs.org/scripts/trespassersW/Yandex-two-columns/issues/%D0%9E%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F_%D0%B4%D0%BB%D1%8F_%D0%B4%D0%BB%D0%B8%D0%BD%D0%BD%D1%8B%D1%85_%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2#comment-15181b17fed)
- Here in this post too
- Userscript version `// @version 3.9.51`

**Comment by trespassersW** [comment]
Google limits the length of translated text; the limit is about 1K bytes or 500 characters in UTF8; thus long texts should be translated  by piecemeal. 
If the limit is exceeded, Google returns 'error 411'.

**Comment by Martii** [comment]
Well that bites... any chance on notifying and clipping the selection down to a word where it stops translating?

**Comment by trespassersW** [comment]
Well, I've  corrected my script. Now the restriction on the length of  text is slightly weakened. (1K letters in any language).
