### ISSUE TITLE
problem with Flash plugin

### ISSUE THREAD

**Issue by byaka** [trespassersW/UserScripts#4]
Chrome 47 + Tampermonkey 3.12.58
In Flash videos event 'MouseUp' not processing correctly.
Please open this link [http://xn--80aacbuczbw9a6a.xn--p1ai/serial-kak-ya-vstretil-vashu-mamu-5-sezon.html](http://xn--80aacbuczbw9a6a.xn--p1ai/serial-kak-ya-vstretil-vashu-mamu-5-sezon.html)
 and try to select episode in right vertical menu.

**Comment by trespassersW** [comment]
Afraid this question not to me
