### ISSUE TITLE
there's some wrong ……

### ISSUE THREAD

**Issue by djj200504001** [trespassersW/UserScripts#5]
well I don't know why that if I use this js,another extensions I use before:https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo
will get some problem.if I right-kick and slid to do an action，it will keep right-kick and show the right-kick list .can you help to slove this problem?

**Comment by djj200504001** [comment]
and so sorry for my poor english :(

**Comment by trespassersW** [comment]
I don't quite understand what it is about.

**Comment by djj200504001** [comment]
well i try to use translation tool to explain this problem
I also use the extended "crxmouse" when using this script
https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo
I found that when at the same time using them
When I right-click to a draw a sign (just like 'down and right ' means 'close this tab'),then release the right mouse button,It does not perform an action,just open the right-click menu and keeping track lines I had draw，then I try to disable this script then it work.
can you help to slove this problem?
PS: I use Tempermonkey to install this script.

**Comment by djj200504001** [comment]
chrome 47.0.2526.106 m

**Comment by trespassersW** [comment]
> When I right-click ..

the script (by design) should not never spoil right-clicks events, Strange, I'll try to figure it out

> I also use the extended "crxmouse" when using this script

 suspect that the problem is somewhere inside <b>jlgkpaicikihijadgifklkbpdajbkhjo </b>

> can you help to slove this problem?

maybe tomorrow

**Comment by trespassersW** [comment]
I apologize, I corrected my script, now it only handles left-click events.

**Comment by djj200504001** [comment]
thank you ! I will keep using this script and help you to find more bugs !
